# Generated by Django 6.1.1 on 2026-10-02 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
